# Generated by Django 4.1.7 on 2023-04-11 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='interactions_little',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='interactions_moderate',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='interactions_severe',
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('S', 'Sever Interaction'), ('M', 'Moderate Interaction'), ('L', 'Little Interaction')], max_length=1)),
                ('med1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_med', to='hospital.medication')),
                ('med2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_med', to='hospital.medication')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='interaction',
            field=models.ManyToManyField(through='hospital.Interactions', to='hospital.medication'),
        ),
    ]
