# Generated by Django 4.1.7 on 2023-04-16 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='interactions',
            name='severity',
            field=models.CharField(choices=[('s', 'Severe Interaction'), ('m', 'Moderate Interaction'), ('l', 'Little Interaction')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(choices=[('ap', 'A Positive'), ('an', 'A Negative'), ('bp', 'B Positive'), ('bn', 'B Negative'), ('abp', 'AB Positive'), ('abn', 'AB Negative'), ('op', 'O Positive'), ('on', 'O Negative')], max_length=30),
        ),
        migrations.CreateModel(
            name='SurgeryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('requirements', models.ManyToManyField(to='hospital.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('code', models.CharField(choices=[('neu', 'Neurosurgery'), ('pod', 'Podiatric Surgery')], max_length=5)),
                ('anatomical_location', models.CharField(choices=[('foot', 'Foot'), ('head', 'Head')], max_length=100)),
                ('category', models.CharField(choices=[('h', 'Requires Hospitalization'), ('o', 'Outpatient')], max_length=100)),
                ('special_needs', models.CharField(max_length=100)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
                ('surgeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.surgeon')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.surgerytype')),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
                ('physician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.physician')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.physician')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.skilledperson')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.skills')),
            ],
        ),
    ]
