# Generated by Django 4.1.7 on 2023-04-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_surgeon_assignedskills_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='surgery_type',
        ),
    ]
