# Generated by Django 4.1.7 on 2023-04-10 22:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hospital.models.people
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Perscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('emp_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salaried',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(25000), django.core.validators.MaxValueValidator(300000)])),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('salaried_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='hospital.salaried')),
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital.person')),
                ('surgery_type', models.CharField(choices=[('Podiatry', 'Podiatry'), ('Optometry', 'Optometry')], max_length=50)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10)),
                ('years_of_experience', models.PositiveIntegerField()),
            ],
            bases=('hospital.person', 'hospital.salaried'),
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('salaried_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='hospital.salaried')),
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital.person')),
                ('specialty', models.CharField(choices=[('Podiatry', 'Podiatry'), ('Optometry', 'Optometry')], max_length=50)),
            ],
            bases=('hospital.person', 'hospital.salaried'),
        ),
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='hospital.contract')),
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital.person')),
            ],
            bases=('hospital.person', 'hospital.contract'),
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.FloatField(max_length=20)),
                ('interactions_little', models.ManyToManyField(to='hospital.medication')),
                ('interactions_moderate', models.ManyToManyField(to='hospital.medication')),
                ('interactions_severe', models.ManyToManyField(to='hospital.medication')),
            ],
        ),
        migrations.CreateModel(
            name='Surgeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('code', models.CharField(choices=[('NEU', 'Neurosurgery'), ('POD', 'Podiatric Surgery')], max_length=5)),
                ('anatomical_location', models.CharField(choices=[('Foot', 'Foot'), ('Head', 'Head')], max_length=100)),
                ('category', models.CharField(choices=[('H', 'Requires Hospitalization'), ('O', 'Outpatient')], max_length=100)),
                ('special_needs', models.CharField(max_length=100)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.nurse')),
                ('surgeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.surgeon')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital.person')),
                ('blood_type', models.CharField(choices=[('OP', 'O Positive'), ('ON', 'O Negative')], max_length=10)),
                ('blood_sugar', models.FloatField()),
                ('cholesterol_hdl', models.FloatField()),
                ('cholesterol_ldl', models.FloatField()),
                ('cholesterol_tri', models.FloatField()),
                ('allergies', models.ManyToManyField(to='hospital.allergy')),
                ('illnesses', models.ManyToManyField(to='hospital.illness')),
                ('pcp', models.ForeignKey(on_delete=models.SET(hospital.models.people.get_chief_of_staff), to='hospital.physician')),
                ('perscribed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medication')),
            ],
            bases=('hospital.person',),
        ),
    ]
