# Generated by Django 4.1.7 on 2023-04-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bed',
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
