# Generated by Django 4.1.7 on 2023-04-10 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_allergy_appointments_contract_illness_perscriptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('transplant', 'Organ Transplants'), ('wound', 'Wound Care')], max_length=50)),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.surgeon')),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('code', models.CharField(choices=[('neu', 'Neurosurgery'), ('pod', 'Podiatric Surgery')], max_length=5)),
                ('anatomical_location', models.CharField(choices=[('foot', 'Foot'), ('head', 'Head')], max_length=100)),
                ('category', models.CharField(choices=[('h', 'Requires Hospitalization'), ('o', 'Outpatient')], max_length=100)),
                ('special_needs', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.ManyToManyField(to='hospital.skills')),
            ],
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='length',
            new_name='contract_length',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='type',
            new_name='contract_type',
        ),
        migrations.AlterField(
            model_name='nurse',
            name='grade',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='surgery_type',
            field=models.CharField(choices=[('podiatry', 'Podiatry'), ('optometry', 'Optometry')], max_length=50),
        ),
        migrations.AlterField(
            model_name='physician',
            name='specialty',
            field=models.CharField(choices=[('podiatry', 'Podiatry'), ('optometry', 'Optometry')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Surgeries',
        ),
        migrations.AddField(
            model_name='surgery',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.nurse'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='surgeon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.surgeon'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.surgerytype'),
        ),
    ]
