# Generated by Django 4.1.7 on 2023-04-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_skills_surgery_surgerytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(choices=[('transplant', 'Organ Transplants'), ('wound', 'Wound Care'), ('brain', 'Brain'), ('head_trauma', 'Head Trauma')], max_length=50),
        ),
    ]
